USE db_chiennes_dog;

CALL sp_insertar_cargo('Administrador');
CALL sp_insertar_cargo('Inventariador');


CALL sp_insertar_administrador('Ana', 'Gómez', 1, 'ana.gomez@example.com', 'clave122');
CALL sp_insertar_administrador('Carlos', 'Rodríguez', 2, 'carlos.rodriguez@example.com', 'clave456');
CALL sp_insertar_administrador('Laura', 'Fernández', 2, 'laura.fernandez@example.com', 'clave789');
CALL sp_insertar_administrador('Pedro', 'Martínez', 1, 'pedro.martinez@example.com', 'claveabc');
CALL sp_insertar_administrador('Sofía', 'López', 2, 'sofia.lopez@example.com', 'clavedef');
CALL sp_insertar_administrador('Juan', 'Sánchez', 2, 'juan.sanchez@example.com', 'claveghi');
CALL sp_insertar_administrador('María', 'Pérez', 1, 'maria.perez@example.com', 'clavejkl');
CALL sp_insertar_administrador('Javier', 'Hernández', 2, 'javier.hernandez@example.com', 'clavemno');
CALL sp_insertar_administrador('Lucía', 'Díaz', 2, 'lucia.diaz@example.com', 'clavepqr');
CALL sp_insertar_administrador('Miguel', 'Moreno', 1, 'miguel.moreno@example.com', 'clavestu');
CALL sp_insertar_administrador('Paula', 'García', 2, 'paula.garcia@example.com', 'clavevwx');
CALL sp_insertar_administrador('Alejandro', 'Lara', 2, 'alejandro.lara@example.com', 'claveyz');
CALL sp_insertar_administrador('Valeria', 'Torres', 1, 'valeria.torres@example.com', 'clave122a');
CALL sp_insertar_administrador('Diego', 'Ruiz', 2, 'diego.ruiz@example.com', 'clave456b');
CALL sp_insertar_administrador('Camila', 'Ramírez', 2, 'camila.ramirez@example.com', 'clave789c');
CALL sp_insertar_administrador('Mateo', 'Gutiérrez', 1, 'mateo.gutierrez@example.com', 'claveabcd');
CALL sp_insertar_administrador('Isabella', 'Cruz', 2, 'isabella.cruz@example.com', 'clavedefg');
CALL sp_insertar_administrador('Daniel', 'Ortega', 2, 'daniel.ortega@example.com', 'claveghij');
CALL sp_insertar_administrador('Elena', 'Reyes', 1, 'elena.reyes@example.com', 'claveklmn');
CALL sp_insertar_administrador('Adrián', 'Castillo', 2, 'adrian.castillo@example.com', 'clavemnop');
CALL sp_insertar_administrador('Bianca', 'Núñez', 2, 'bianca.nunez@example.com', 'clavepqrst');
CALL sp_insertar_administrador('Gabriel', 'Guerrero', 1, 'gabriel.guerrero@example.com', 'claveuvwxy');
CALL sp_insertar_administrador('Sara', 'Mendoza', 2, 'sara.mendoza@example.com', 'clavez122');
CALL sp_insertar_administrador('Matías', 'Silva', 2, 'matias.silva@example.com', 'clave456a');
CALL sp_insertar_administrador('Olivia', 'Herrera', 1, 'olivia.herrera@example.com', 'clave789b');
CALL sp_insertar_administrador('Leonardo', 'Santos', 2, 'leonardo.santos@example.com', 'claveabca');


CALL sp_insertar_cliente('Ana', 'Gómez', '123456789', 'ana.gomez@example.com', '111111111', '1990-05-12', 'Calle 1, Ciudad', 'clave123');
CALL sp_insertar_cliente('Carlos', 'Rodríguez', '987654321', 'carlos.rodriguez@example.com', '222222222', '1988-08-18', 'Avenida 2, Villa', 'clave456');
CALL sp_insertar_cliente('Laura', 'Fernández', '456789012', 'laura.fernandez@example.com', '333333333', '1995-02-25', 'Calle 3, Pueblo', 'clave789');
CALL sp_insertar_cliente('Pedro', 'Martínez', '111222333', 'pedro.martinez@example.com', '444444444', '1992-07-30', 'Avenida 4, Ciudad', 'claveabc');
CALL sp_insertar_cliente('Sofía', 'López', '444555666', 'sofia.lopez@example.com', '555555555', '1987-12-05', 'Calle 5, Villa', 'clavedef');
CALL sp_insertar_cliente('Juan', 'Sánchez', '777888999', 'juan.sanchez@example.com', '666666666', '1998-10-15', 'Avenida 6, Pueblo', 'claveghi');
CALL sp_insertar_cliente('María', 'Pérez', '222333444', 'maria.perez@example.com', '777777777', '1984-04-20', 'Calle 7, Ciudad', 'clavejkl');
CALL sp_insertar_cliente('Javier', 'Hernández', '555666777', 'javier.hernandez@example.com', '888888888', '1993-09-08', 'Avenida 8, Villa', 'clavemno');
CALL sp_insertar_cliente('Lucía', 'Díaz', '888999000', 'lucia.diaz@example.com', '999999999', '1989-11-28', 'Calle 9, Pueblo', 'clavepqr');
CALL sp_insertar_cliente('Miguel', 'Moreno', '333444555', 'miguel.moreno@example.com', '101010101', '1996-01-03', 'Avenida 10, Ciudad', 'clavestu');
CALL sp_insertar_cliente('Paula', 'García', '000111222', 'paula.garcia@example.com', '111122223', '1991-06-14', 'Calle 11, Villa', 'clavevwx');
CALL sp_insertar_cliente('Alejandro', 'Lara', '666777888', 'alejandro.lara@example.com', '222233334', '1994-03-19', 'Avenida 12, Pueblo', 'claveyz');
CALL sp_insertar_cliente('Valeria', 'Torres', '111000999', 'valeria.torres@example.com', '333344445', '1986-08-22', 'Calle 13, Ciudad', 'clave123a');
CALL sp_insertar_cliente('Diego', 'Ruiz', '999888777', 'diego.ruiz@example.com', '444455556', '1997-04-07', 'Avenida 14, Villa', 'clave456b');
CALL sp_insertar_cliente('Camila', 'Ramírez', '222111000', 'camila.ramirez@example.com', '555566667', '1985-09-10', 'Calle 15, Pueblo', 'clave789c');
CALL sp_insertar_cliente('Mateo', 'Gutiérrez', '555444333', 'mateo.gutierrez@example.com', '666677778', '1990-12-25', 'Avenida 16, Ciudad', 'claveabcd');
CALL sp_insertar_cliente('Isabella', 'Cruz', '888777666', 'isabella.cruz@example.com', '999988887', '1995-02-02', 'Calle 17, Villa', 'clavedefg');
CALL sp_insertar_cliente('Daniel', 'Ortega', '911222333', 'daniel.ortega@example.com', '123012301', '1992-07-30', 'Avenida 18, Pueblo', 'claveghij');
CALL sp_insertar_cliente('Elena', 'Reyes', '644555666', 'elena.reyes@example.com', '456123012', '1987-04-15', 'Calle 19, Ciudad', 'claveklmn');
CALL sp_insertar_cliente('Adrián', 'Castillo', '177888999', 'adrian.castillo@example.com', '789456123', '1998-09-28', 'Avenida 20, Villa', 'clavemnop');
CALL sp_insertar_cliente('Bianca', 'Núñez', '282333444', 'bianca.nunez@example.com', '012345678', '1984-11-05', 'Calle 21, Pueblo', 'clavepqrst');
CALL sp_insertar_cliente('Gabriel', 'Guerrero', '565666777', 'gabriel.guerrero@example.com', '234567890', '1993-03-18', 'Avenida 22, Ciudad', 'claveuvwxy');
CALL sp_insertar_cliente('Sara', 'Mendoza', '888199000', 'sara.mendoza@example.com', '345678901', '1996-06-29', 'Calle 23, Villa', 'clavez123');
CALL sp_insertar_cliente('Matías', 'Silva', '111900999', 'matias.silva@example.com', '456789012', '1989-01-12', 'Avenida 24, Pueblo', 'clave456a');
CALL sp_insertar_cliente('Olivia', 'Herrera', '646777888', 'olivia.herrera@example.com', '567890123', '1994-08-25', 'Calle 25, Ciudad', 'clave789b');
CALL sp_insertar_cliente('Leonardo', 'Santos', '999788777', 'leonardo.santos@example.com', '678901234', '1985-02-08', 'Avenida 26, Villa', 'claveabca');

SELECT * FROM tb_clientes;


CALL sp_insertar_marca('Sumsu', 'imagen1.jpg');
CALL sp_insertar_marca('Pedigree', 'imagen2.jpg');
CALL sp_insertar_marca('Kong', 'imagen3.jpg');
CALL sp_insertar_marca('Hill\'s Science Diet', 'imagen1.jpg');
CALL sp_insertar_marca('Royal Canin', 'imagen2.jpg');
CALL sp_insertar_marca('Blue Buffalo', 'imagen3.jpg');
CALL sp_insertar_marca('Iams', 'imagen4.jpg');
CALL sp_insertar_marca('Purina Pro Plan', 'imagen5.jpg');
CALL sp_insertar_marca('Nutro', 'imagen6.jpg');
CALL sp_insertar_marca('Merrick', 'imagen7.jpg');
CALL sp_insertar_marca('Canidae', 'imagen8.jpg');
CALL sp_insertar_marca('Wellness', 'imagen9.jpg');
CALL sp_insertar_marca('Pedigree', 'imagen10.jpg');
CALL sp_insertar_marca('Orijen', 'imagen11.jpg');
CALL sp_insertar_marca('Monge', 'imagen12.jpg');
CALL sp_insertar_marca('Acana', 'imagen13.jpg');
CALL sp_insertar_marca('Natural Balance', 'imagen14.jpg');
CALL sp_insertar_marca('Hill\'s Prescription Diet', 'imagen15.jpg');
CALL sp_insertar_marca('Merrick Grain-Free', 'imagen16.jpg');
CALL sp_insertar_marca('Holistic Select', 'imagen17.jpg');
CALL sp_insertar_marca('Taste of the Wild', 'imagen18.jpg');
CALL sp_insertar_marca('Canine Caviar', 'imagen19.jpg');
CALL sp_insertar_marca('Wild Earth', 'imagen20.jpg');
CALL sp_insertar_marca('Zignature', 'imagen21.jpg');
CALL sp_insertar_marca('Fromm Family Foods', 'imagen22.jpg');
CALL sp_insertar_marca('Nulo', 'imagen23.jpg');
CALL sp_insertar_marca('Rachael Ray Nutrish', 'imagen24.jpg');
CALL sp_insertar_marca('Petcurean', 'imagen25.jpg');


CALL sp_insertar_categoria('Alimentos');
CALL sp_insertar_categoria('Juguetes');
CALL sp_insertar_categoria('Ropa');
CALL sp_insertar_categoria('Cosméticos y peluquería');
CALL sp_insertar_categoria('Accesorios');
CALL sp_insertar_categoria('Descanso');


CALL sp_insertar_producto(1, 'Collar Ajustable para Perros', 1, 'Collar ajustable con hebilla resistente. Disponible en varios colores. Ideal para perros de todos los tamaños.', 14.99, 'imagen1.jpg', true, 120, 1);
CALL sp_insertar_producto(2, 'Juguete Pelota de Goma', 2, 'Pelota de goma resistente para juegos interactivos. Perfecta para masticar y mantener a tu perro activo y entretenido.', 8.99, 'imagen2.jpg', true, 90, 2);
CALL sp_insertar_producto(3, 'Snack Natural para Perros', 3, 'Deliciosos snacks naturales con ingredientes de alta calidad. Sin aditivos artificiales. Una opción saludable y sabrosa.', 12.99, 'imagen3.jpg', true, 150, 3);
CALL sp_insertar_producto(4, 'Arnés Acolchado para Paseos', 1, 'Arnés acolchado con cierre de clic para paseos cómodos. Diseño ergonómico para evitar tirones. Disponible en diferentes tallas.', 19.99, 'imagen4.jpg', true, 80, 1);
CALL sp_insertar_producto(5, 'Peluche de Juguete para Perros', 2, 'Peluche suave y divertido para horas de juego. Resistente y seguro para perros de todas las edades. Ideal para abrazar y masticar.', 11.99, 'imagen5.jpg', true, 110, 2);
CALL sp_insertar_producto(6, 'Comida Seca Premium', 3, 'Alimento seco premium con ingredientes seleccionados. Fórmula balanceada para satisfacer las necesidades nutricionales de tu perro. Disponible en diferentes sabores.', 34.99, 'imagen6.jpg', true, 100, 3);
CALL sp_insertar_producto(1, 'Chaleco de Seguridad Reflectante', 1, 'Chaleco reflectante para mayor visibilidad durante paseos nocturnos. Ajustable y cómodo. Garantiza la seguridad de tu perro en la oscuridad.', 21.99, 'imagen7.jpg', true, 130, 1);
CALL sp_insertar_producto(2, 'Juguete de Cuerda para Tirar', 2, 'Juguete de cuerda resistente para juegos de tirar. Fomenta la actividad física y fortalece la mandíbula. Apto para perros de todas las razas.', 13.99, 'imagen8.jpg', true, 95, 2);
CALL sp_insertar_producto(3, 'Galletas Naturales para Perros', 3, 'Galletas naturales horneadas con ingredientes saludables. Deliciosas y nutritivas como premios o snacks entre comidas.', 9.49, 'imagen9.jpg', true, 120, 3);
CALL sp_insertar_producto(1, 'Cama Ortopédica para Perros', 1, 'Cama ortopédica con memoria viscoelástica para el descanso óptimo de tu perro. Diseño lavable y duradero. Disponible en varios tamaños.', 45.99, 'imagen10.jpg', true, 70, 1);
CALL sp_insertar_producto(1, 'Pelota con Dispensador de Golosinas', 2, 'Pelota interactiva con compartimiento para golosinas. Estimula la mente y la destreza. Ideal para recompensas durante el juego.', 16.99, 'imagen11.jpg', true, 85, 2);
CALL sp_insertar_producto(2, 'Cepillo de Dientes para Perros', 3, 'Cepillo de dientes diseñado para la higiene dental de tu perro. Ayuda a prevenir problemas bucales y mantener un aliento fresco.', 7.99, 'imagen12.jpg', true, 140, 3);
CALL sp_insertar_producto(3, 'Comedero Antideslizante', 1, 'Comedero resistente y antideslizante para facilitar la alimentación. Diseño moderno y fácil de limpiar. Disponible en varios colores.', 10.49, 'imagen13.jpg', true, 110, 1);
CALL sp_insertar_producto(4, 'Juguete de Peluche con Sonido', 2, 'Peluche con sonido para una diversión extra. Suave y seguro para masticar. Perfecto para perros juguetones.', 14.99, 'imagen14.jpg', true, 100, 2);
CALL sp_insertar_producto(5, 'Kit de Cuidado y Aseo', 3, 'Kit completo de cuidado y aseo para perros. Incluye cepillo, champú, cortaúñas y más. Todo lo necesario para mantener a tu perro limpio y saludable.', 27.99, 'imagen15.jpg', true, 120, 3);
CALL sp_insertar_producto(6, 'Chaqueta de Invierno para Perros', 1, 'Chaqueta abrigada y resistente al agua para proteger a tu perro en invierno. Con forro térmico y cierre ajustable.', 32.99, 'imagen16.jpg', true, 75, 1);
CALL sp_insertar_producto(1, 'Juguete Dispensador de Golosinas', 2, 'Juguete interactivo que dispensa golosinas mientras juega. Estimula la actividad mental y física. Ideal para perros activos.', 18.99, 'imagen17.jpg', true, 105, 2);
CALL sp_insertar_producto(1, 'Bolso de Viaje para Perros', 3, 'Bolso de viaje cómodo y seguro para transportar a tu perro. Con ventilación y bolsillos adicionales. Perfecto para salidas y excursiones.', 29.99, 'imagen18.jpg', true, 90, 3);
CALL sp_insertar_producto(1, 'Correa de Entrenamiento', 1, 'Correa resistente con asa acolchada. Ideal para entrenamiento y paseos diarios. Ajustable para diferentes longitudes.', 15.99, 'imagen19.jpg', true, 115, 1);
CALL sp_insertar_producto(4, 'Juguete de Entrenamiento Inteligente', 2, 'Juguete interactivo que desafía la mente de tu perro. Dispensa golosinas y estimula el pensamiento.', 17.99, 'imagen47.jpg', true, 105, 2);
CALL sp_insertar_producto(4, 'Comida Húmeda Gourmet', 3, 'Comida húmeda gourmet con sabores exquisitos. Elaborada con ingredientes de alta calidad para satisfacer los paladares más exigentes.', 22.99, 'imagen48.jpg', true, 90, 3);
CALL sp_insertar_producto(4, 'Mochila para Perros Pequeños', 1, 'Mochila cómoda y segura para llevar a tu perro en tus aventuras. Adecuada para perros pequeños y medianos.', 27.99, 'imagen49.jpg', true, 115, 1);
CALL sp_insertar_producto(5, 'Juguete para Tiro y Jalón', 2, 'Juguete resistente para juegos de tiro y jalón. Fortalece los músculos y proporciona ejercicio divertido.', 15.99, 'imagen50.jpg', true, 140, 2);
CALL sp_insertar_producto(1, 'Collar Reflectante para Perros', 1, 'Collar ajustable con material reflectante para mayor visibilidad durante paseos nocturnos. Ideal para perros de todos los tamaños.', 15.99, 'imagen1.jpg', true, 100, 1);
CALL sp_insertar_producto(2, 'Juguete Masticable Dental', 2, 'Juguete interactivo diseñado para promover la salud dental de tu perro. Ayuda a prevenir la acumulación de placa y fortalece las encías.', 12.99, 'imagen2.jpg', true, 150, 2);


CALL sp_insertar_pedido(1, 'Entregado', 'Calle Principal #123');
CALL sp_insertar_pedido(2, 'Pendiente', 'Avenida Central #456');
CALL sp_insertar_pedido(3, 'Pendiente', 'Calle Secundaria #789');
CALL sp_insertar_pedido(4, 'Entregado', 'Avenida Norte #234');
CALL sp_insertar_pedido(5, 'Pendiente', 'Calle Este #567');
CALL sp_insertar_pedido(6, 'Entregado', 'Avenida Oeste #890');
CALL sp_insertar_pedido(7, 'Entregado', 'Calle Principal #111');
CALL sp_insertar_pedido(8, 'Pendiente', 'Avenida Central #222');
CALL sp_insertar_pedido(9, 'Entregado', 'Calle Secundaria #333');
CALL sp_insertar_pedido(10, 'Pendiente', 'Avenida Norte #444');
CALL sp_insertar_pedido(11, 'Entregado', 'Calle Este #555');
CALL sp_insertar_pedido(12, 'Pendiente', 'Avenida Oeste #666');
CALL sp_insertar_pedido(13, 'Entregado', 'Calle Principal #777');
CALL sp_insertar_pedido(14, 'Pendiente', 'Avenida Central #888');
CALL sp_insertar_pedido(15, 'Entregado', 'Calle Secundaria #999');
CALL sp_insertar_pedido(16, 'Entregado', 'Avenida Norte #1010');
CALL sp_insertar_pedido(17, 'Pendiente', 'Calle Este #1212');
CALL sp_insertar_pedido(18, 'Entregado', 'Avenida Oeste #1313');
CALL sp_insertar_pedido(19, 'Pendiente', 'Calle Principal #1414');
CALL sp_insertar_pedido(20, 'Entregado', 'Avenida Central #1515');
CALL sp_insertar_pedido(21, 'Pendiente', 'Calle Secundaria #1616');
CALL sp_insertar_pedido(22, 'Entregado', 'Avenida Norte #1717');
CALL sp_insertar_pedido(23, 'Pendiente', 'Calle Este #1818');
CALL sp_insertar_pedido(24, 'Entregado', 'Avenida Oeste #1919');
CALL sp_insertar_pedido(25, 'Entregado', 'Calle Principal #2020');


CALL sp_insertar_detalle_pedido(1, 1, 2, 29.99);
CALL sp_insertar_detalle_pedido(1, 3, 1, 12.99);
CALL sp_insertar_detalle_pedido(2, 2, 3, 19.99);
CALL sp_insertar_detalle_pedido(2, 4, 1, 14.99);
CALL sp_insertar_detalle_pedido(3, 5, 2, 25.99);
CALL sp_insertar_detalle_pedido(3, 1, 1, 14.99);
CALL sp_insertar_detalle_pedido(4, 3, 3, 39.99);
CALL sp_insertar_detalle_pedido(4, 4, 2, 22.99);
CALL sp_insertar_detalle_pedido(5, 2, 1, 9.99);
CALL sp_insertar_detalle_pedido(5, 5, 2, 17.99);
CALL sp_insertar_detalle_pedido(6, 1, 3, 32.99);
CALL sp_insertar_detalle_pedido(6, 3, 1, 15.99);
CALL sp_insertar_detalle_pedido(7, 4, 2, 19.99);
CALL sp_insertar_detalle_pedido(7, 2, 1, 11.99);
CALL sp_insertar_detalle_pedido(8, 5, 3, 28.99);
CALL sp_insertar_detalle_pedido(8, 1, 2, 14.99);
CALL sp_insertar_detalle_pedido(9, 2, 1, 9.99);
CALL sp_insertar_detalle_pedido(9, 3, 2, 18.99);
CALL sp_insertar_detalle_pedido(10, 4, 3, 29.99);
CALL sp_insertar_detalle_pedido(10, 5, 1, 13.99);
CALL sp_insertar_detalle_pedido(11, 1, 2, 23.99);
CALL sp_insertar_detalle_pedido(11, 2, 1, 12.99);
CALL sp_insertar_detalle_pedido(12, 3, 3, 35.99);
CALL sp_insertar_detalle_pedido(12, 4, 2, 21.99);
CALL sp_insertar_detalle_pedido(13, 5, 1, 11.99);


CALL sp_insertar_valoracion(4);
CALL sp_insertar_valoracion(5);
CALL sp_insertar_valoracion(3);
CALL sp_insertar_valoracion(4);
CALL sp_insertar_valoracion(2);
CALL sp_insertar_valoracion(5);
CALL sp_insertar_valoracion(4);
CALL sp_insertar_valoracion(3);
CALL sp_insertar_valoracion(5);
CALL sp_insertar_valoracion(4);
CALL sp_insertar_valoracion(3);
CALL sp_insertar_valoracion(5);
CALL sp_insertar_valoracion(4);
CALL sp_insertar_valoracion(2);
CALL sp_insertar_valoracion(4);
CALL sp_insertar_valoracion(5);
CALL sp_insertar_valoracion(3);
CALL sp_insertar_valoracion(4);
CALL sp_insertar_valoracion(3);
CALL sp_insertar_valoracion(5);
CALL sp_insertar_valoracion(4);
CALL sp_insertar_valoracion(4);
CALL sp_insertar_valoracion(5);
CALL sp_insertar_valoracion(3);
CALL sp_insertar_valoracion(4);
CALL sp_insertar_valoracion(2);


CALL sp_insertar_valoracion_producto(1, 1);
CALL sp_insertar_valoracion_producto(2, 2);
CALL sp_insertar_valoracion_producto(3, 3);
CALL sp_insertar_valoracion_producto(4, 4);
CALL sp_insertar_valoracion_producto(5, 5);
CALL sp_insertar_valoracion_producto(6, 6);
CALL sp_insertar_valoracion_producto(7, 7);
CALL sp_insertar_valoracion_producto(8, 8);
CALL sp_insertar_valoracion_producto(9, 9);
CALL sp_insertar_valoracion_producto(10, 10);
CALL sp_insertar_valoracion_producto(11, 11);
CALL sp_insertar_valoracion_producto(12, 12);
CALL sp_insertar_valoracion_producto(13, 13);
CALL sp_insertar_valoracion_producto(14, 14);
CALL sp_insertar_valoracion_producto(15, 15);
CALL sp_insertar_valoracion_producto(16, 16);
CALL sp_insertar_valoracion_producto(17, 17);
CALL sp_insertar_valoracion_producto(18, 18);
CALL sp_insertar_valoracion_producto(19, 19);
CALL sp_insertar_valoracion_producto(20, 20);
CALL sp_insertar_valoracion_producto(21, 21);
CALL sp_insertar_valoracion_producto(22, 22);
CALL sp_insertar_valoracion_producto(23, 23);
CALL sp_insertar_valoracion_producto(24, 24);
CALL sp_insertar_valoracion_producto(25, 25);
